name: Node.js CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      # Step 3: Install dependencies and Jest for backend
      - name: Install dependencies (backend)
        run: npm install && npm install --save-dev jest

      # Step 4: Install dependencies and Jest for frontend
      - name: Install dependencies (frontend)
        working-directory: ./client
        run: npm install && npm install --save-dev jest

      # Step 5: Set up environment variables from GitHub Secrets
      - name: Setup environment variables
        run: |
          echo "NODE_ENV=production" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}"
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}"
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      # Step 5: Run tests
      - name: Run tests
        run: npm test