name: Node.js CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      # Step 3: Install dependencies and Jest for backend
      - name: Install dependencies (backend)
        working-directory: ./
        run: npm install && npm install --save-dev jest

      # Step 4: Install dependencies and Jest for frontend
      - name: Install dependencies (frontend)
        working-directory: ./client
        run: npm install && npm install --save-dev jest

      # Step 5: Run tests
      - name: Run tests
        working-directory: ./
        run: npm run test